"""empty message

Revision ID: f841666819a6
Revises: ad07b95f2359
Create Date: 2024-05-20 01:03:29.942647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f841666819a6'
down_revision = 'ad07b95f2359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_lost_items',
    sa.Column('find_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('contents', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('location_of_discovery', sa.String(length=255), nullable=True),
    sa.Column('time_of_discovery', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('find_id')
    )
    op.create_table('report_lost_item',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('contents', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('location_of_discovery', sa.String(length=255), nullable=True),
    sa.Column('time_of_discovery', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_lost_item')
    op.drop_table('finding_lost_items')
    # ### end Alembic commands ###
